# Generated by Django 3.1 on 2020-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=50)),
                ('comment_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
